name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.2"

      - name: Check formatting
        if: matrix.os != 'windows-latest'
        run: zig fmt --check build.zig src/

      - name: Run tests
        run: zig build test --summary all
